version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 95126688
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:95126688@db:5432/postgres
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port $PORT"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
 
